development:
  adapter: postgresql
  encoding: unicode
  database: kaihoko_development
  pool: 5
  username: nickj

test:
  adapter: postgresql
  encoding: unicode
  database: kaihoko_test
  pool: 5
  username: nickj
